src/components.d.ts, src/components/__mock__/config.ts, src/components/pie-author/__tests__/pie-author.e2e.ts, src/components/pie-author/pie-author.tsx, src/components/test-util/mockPieCloudResponse.js
enhanced test and removed redundant updates to model.
=> fix: updateModels event should be fired on initialization

src/pie-loader.ts
This temoporary fix disables the use of
pie_registry when using `loadPlayerJson` (which will have a bundle.url property in model) this
reverts to how things were before. But this
should be changed to use an enhanced registry
to help optimize and not double-load PIEs.
The bug was that the registry thought it had
loaded the PIE but the bundle was player.js
which does not have Config constructor
=> fix: authoring view not loading PIE-155

src/components/pie-author/pie-author.tsx, src/components/pie-loader/pie-loader.tsx, src/components/pie-player/pie-player.tsx, src/pie-loader.ts
(and default it to false for now)
=> feat: make use of hash with  pie cdn an optional feature

src/components/pie-player/pie-player.tsx, src/demo/dupes.html
fix players rendering duplicate when
resetting config for stimulus layout
=> fix: dupe players

package.json, release.config.js
Adds integration with JIRA issue tracker for semantic releases
=> feat: jira semantic release PD-80

src/components/components.css
https://illuminate.atlassian.net/browse/PD-876
=> fix: define classes for tables and table elements - PD-876 

src/components/components.css
https://illuminate.atlassian.net/browse/PD-774
=> fix: override font style for mjx to fix PD-774

src/components/components.css, src/demo/pd-232.html
https://illuminate.atlassian.net/browse/PD-1148
=> fix: override style for math PD-1148

src/components/components.css
https://illuminate.atlassian.net/browse/PD-965
=> fix: minor math rendering issues with quotes PD-965

src/components/components.css
https://illuminate.atlassian.net/browse/PD-482
=> fix: add style for IBX user authored math PD-482

src/components/pie-author/pie-author.tsx
https://illuminate.atlassian.net/browse/PD-1910
=> fix: validation method

package.json, src/components/pie-author/pie-author.tsx, yarn.lock
https://illuminate.atlassian.net/browse/PD-1960
=> fix: don't fire file input click if image is pasted

src/components/pie-author/pie-author.tsx, src/demo/utils/models.js, src/rubric-utils.ts
BREAKING CHANGE: automatically add complex-rubric
The author will automatically add/remove the new item type (complex-rubric) depending on the value of a new property from models (rubricEnabled: Boolean)
=> feat: add complex-rubric to item config

.circleci/config.yml, src/components/__mock__/config.ts, src/components/pie-player/pie-player.tsx, src/demo/author-preview-complex-rubric-with-defaults.html, src/demo/complex-rubric-use-cases.html, src/demo/dupes.html, src/demo/dups.html, src/demo/player.html, src/demo/stimulus-no-render.html, src/interface.d.ts
BREAKING CHANGE: stimulus property inside item config was replaced with passage property.
=> feat: replace stimulus with passage to work with new pie-api-aws PD-2909

package.json, yarn.lock
Reverts pie-framework/pie-player-components#138
=> Revert "fix: use latest pie-lib/math-rendering"

package.json, src/components/pie-author/pie-author.tsx, src/components/pie-player/pie-player.tsx, yarn.lock
Reverts pie-framework/pie-player-components#147
=> Revert "feat: use pie-lib/pie-toolbox instead of pie-lib/math-rendering"

src/components/pie-player/pie-player.tsx, src/demo/author-proxy-dev.html, src/demo/author-proxy-prod.html, src/demo/player-proxy-dev.html, src/demo/player-proxy-prod.html, src/pie-loader.ts
I needed to provide a fix for the player, the values were not passed on in the render function.
The author worked as expected, changing the bundleEndpoints and making the request to the correct URLs
=> feat: add proxy url for production PD-3670

src/__tests__/pie-loader.spec.ts, src/pie-loader.ts, src/utils/utils.ts
https://illuminate.atlassian.net/browse/PD-3808
=> fix(pie-loader): add fetch retry functionality for pie scripts PD-3808

src/components/pie-author/pie-author.tsx
https://illuminate.atlassian.net/browse/PD-3863
=> fix: prevent updating item if not needed (infinite loop on ebsr) PD-3863

src/pie-loader.ts
https://illuminate.atlassian.net/browse/PD-3907
=> fix(pie-loader): added missing script type attribute PD-3907

src/components/pie-author/pie-author.tsx, src/demo/complex-rubric-with-missing-markup.html, src/rubric-utils.ts
https://illuminate.atlassian.net/browse/PD-3218
=> fix(complex-rubric): fix model values on force rubric conversion PD-3218

src/components/pie-author/pie-author.tsx
https://illuminate.atlassian.net/browse/PD-3634
=> fix: made sure fileinput cancel is handled [PD-3634]

src/components/pie-author/pie-author.tsx, src/demo/multiple-choice-validation.html
fix: made sure image upload works PD-4013
https://illuminate.atlassian.net/browse/PD-4013
=> fix: made sure image upload works PD-4013

src/components/components.css
https://illuminate.atlassian.net/browse/PD-3658
=> fix: Added !important to .pie-api-player img max-width and max-height for consistent styling

src/components/pie-player/pie-player.tsx, src/demo/test-new-relic.html, src/new-relic.ts, src/pie-loader.ts, src/utils/utils.ts
https://illuminate.atlassian.net/browse/PD-4939
=> feat(new-relic): add new relic support PD-4939

src/components/pie-stimulus-layout/pie-stimulus-layout.css, src/components/pie-stimulus-layout/pie-stimulus-layout.tsx
https://illuminate.atlassian.net/browse/PD-4526
=> feat(pie-stimulus-layout): adjust viewport threshold for layout switch to 1020px PD-4526

src/demo/item-provide-score.html, src/pie-loader.ts, src/utils/utils.ts
https://illuminate.atlassian.net/browse/PD-5073
=> feat: retry bundle fetching for any error PD-5073
